language: python 
python:
  - "3.6"
branches:
  only:
    - master
addons:
  apt:
    packages:
    - r-base-dev
    - r-recommended
    - pandoc
cache:
  directories: 
    - ~/Rlib
# Setup anaconda
install: 
  # - sudo apt-get update
  #- export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -f environment.yml
  - source activate 2020plus
  - conda install r r-randomForest rpy2
  - pip install nose
  #- conda create -q -n test-environment numpy scipy nose pandas scikit-learn tzlocal
  #- source activate test-environment
  #- conda install -c r r-essentials
  #- conda install -c r r-randomForest
  - R --version
  #- conda install rpy2;
script: "nosetests tests/test_train.py tests/test_classify.py tests/test_features.py"
