name: 2020plus
channels:
- bioconda
- defaults
dependencies:
- numpy
- scipy<1.0.0
- matplotlib
- pandas<1.0.0
- scikit-learn<0.20.0
- pyyaml
- pysam
- snakemake
- tzlocal
- pip
- pip:
  - probabilistic2020
